# Generated by Django 4.0.6 on 2022-07-22 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0002_framework'),
    ]

    operations = [
        migrations.RenameField(
            model_name='framework',
            old_name='code_wirter',
            new_name='Language',
        ),
        migrations.RenameField(
            model_name='language',
            old_name='code_wirter',
            new_name='producer',
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('framework', models.ManyToManyField(to='relations.framework')),
            ],
        ),
    ]
